plugins {
    id 'java'
    id 'fabric-loom' version '1.7-SNAPSHOT'
}

version = "3.0.0"
group = "net.denmoth.createstructuresoverhaul"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://mvn.devos.one/snapshots/" } // Create Fabric
    maven { url = "https://raw.githubusercontent.com/Fuzss/modrinth/main/maven/" } // Forge Config API Port
    maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
    maven { url = "https://maven.terraformersmc.com/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings loom.officialMojangMappings()
    
    modImplementation "net.fabricmc:fabric-loader:0.15.11"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.2+1.20.1"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def expandProps = [
        "mod_id": "cso",
        "mod_version": "3.0.0",
        "mod_name": "Create: Structures Overhaul",
        "mod_license": "MIT",
        "mod_authors": "Denmoth",
        "mod_description": "Overhauls exploration by adding immersive, Create-themed structures to the world.",
        "loader_version_range": "[47,)",
        "minecraft_version_range": "[1.20.1]",
        "forge_version_range": "[47,)",
        "neoforge_version_range": "[1.20.1,)"
    ]
    inputs.properties expandProps
    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
}

jar {
    exclude 'net/minecraftforge/**'
    exclude 'net/neoforged/**'
}