plugins {
    id 'java'
    id 'dev.architectury.loom' version '1.7-SNAPSHOT'
}

version = "3.0.0"
group = "net.denmoth.createstructuresoverhaul"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

sourceSets {
    main {
        resources {
            srcDir project.file('../common/src/main/resources')
        }
        java {
            srcDir project.file('../common/src/main/java')
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://maven.minecraftforge.net/" }
    maven { url = "https://maven.tterrag.com/" }
    maven { url = "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings loom.officialMojangMappings()

    forge "net.minecraftforge:forge:1.20.1-47.1.3"
    
    // Optional Cloth Config API
    modCompileOnly "me.shedaniel.cloth:cloth-config-forge:11.1.118"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def expandProps = [
        "mod_id": "cso",
        "mod_version": "3.0.0",
        "mod_name": "Create: Structures Overhaul",
        "mod_license": "MIT",
        "mod_authors": "Denmoth",
        "mod_description": "Overhauls exploration by adding immersive, Create-themed structures to the world.",
        "loader_version_range": "[47,)",
        "minecraft_version_range": "[1.20.1]",
        "forge_version_range": "[47,)",
        "neoforge_version_range": "[1.20.1,)"
    ]
    inputs.properties expandProps
    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
}

jar {
    exclude 'net/minecraftforge/**'
    exclude 'net/neoforged/**'
}