modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="create_structures_overhaul"
version="1.1.0"
displayName="Create: Structures overhaul"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/create-structures-overrhaul"
logoFile="logo.png"
credits="Creator - Denmoth; builder - timy228e"
authors="Denmoth"
description="This mod adding some structures to create mod"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_structures_overhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_structures_overhaul]]
    modId="create"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration
