package net.denmoth.createstructuresoverhaul.datagen;

import net.denmoth.createstructuresoverhaul.CreateStructuresOverhaulMod;
import net.minecraft.data.PackOutput;
import net.minecraftforge.common.data.LanguageProvider;

public class ModLanguageProvider {

    // Хелпер обновлен: добавлены Ghostbuster (spookAll) и Heavy Industry (indAll)
    private static void addCommon(LanguageProvider provider, String title,
                                  String rootT, String rootD,
                                  String windT, String windD,
                                  String windAllT, String windAllD,
                                  String spookT, String spookD,
                                  String spookAllT, String spookAllD, // <-- NEW
                                  String indT, String indD,
                                  String indAllT, String indAllD,     // <-- NEW
                                  String tradeT, String tradeD,
                                  String netherT, String netherD,
                                  String invT, String invD,
                                  String allT, String allD,
                                  String mapH, String mapN) {

        provider.add("itemGroup.create_structures_overhaul", title);
        provider.add("advancements.cso.root.title", rootT);
        provider.add("advancements.cso.root.desc", rootD);
        provider.add("advancements.cso.windmills.title", windT);
        provider.add("advancements.cso.windmills.desc", windD);
        provider.add("advancements.cso.windmills_all.title", windAllT);
        provider.add("advancements.cso.windmills_all.desc", windAllD);
        provider.add("advancements.cso.spooky.title", spookT);
        provider.add("advancements.cso.spooky.desc", spookD);
        provider.add("advancements.cso.spooky_all.title", spookAllT); // <-- NEW
        provider.add("advancements.cso.spooky_all.desc", spookAllD);   // <-- NEW
        provider.add("advancements.cso.industrial.title", indT);
        provider.add("advancements.cso.industrial.desc", indD);
        provider.add("advancements.cso.industrial_all.title", indAllT); // <-- NEW
        provider.add("advancements.cso.industrial_all.desc", indAllD);  // <-- NEW
        provider.add("advancements.cso.trading.title", tradeT);
        provider.add("advancements.cso.trading.desc", tradeD);
        provider.add("advancements.cso.nether.title", netherT);
        provider.add("advancements.cso.nether.desc", netherD);
        provider.add("advancements.cso.invasion.title", invT);
        provider.add("advancements.cso.invasion.desc", invD);
        provider.add("advancements.cso.all.title", allT);
        provider.add("advancements.cso.all.desc", allD);
        provider.add("item.cso.haunted_map", mapH);
        provider.add("item.cso.nether_map", mapN);
    }

    // ================= ENGLISH FAMILY =================
    public static class EN extends LanguageProvider { public EN(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_us"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "The Age of Excavation", "Welcome to the world of industrial ruins.", "Don Quixote", "Find any abandoned windmill.", "Lord of the Winds", "Visit every type of windmill.", "Ghost Story", "Discover a haunted location.", "Ghostbuster", "Survive every haunted structure.", "Rusty Ruins", "Find an industrial remnant.", "Heavy Industry", "Visit every industrial remnant.", "Cartography", "Buy a structure map from a Cartographer.", "Hellish Expansion", "Find a structure in the Nether.", "Dimensional Breach", "Find a Nether structure in the Overworld.", "The Grand Tour", "Visit every single structure added by the mod.", "Haunted Explorer Map", "Nether Explorer Map"); } }
    public static class EN_GB extends LanguageProvider { public EN_GB(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_gb"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "The Age of Excavation", "Welcome to the world of industrial ruins.", "Don Quixote", "Find any abandoned windmill.", "Lord of the Winds", "Visit every colour and type of windmill.", "Ghost Story", "Discover a haunted location.", "Ghostbuster", "Survive every haunted structure.", "Rusty Ruins", "Find an industrial remnant.", "Heavy Industry", "Visit every industrial remnant.", "Cartography", "Buy a structure map from a Cartographer.", "Hellish Expansion", "Find a structure in the Nether.", "Dimensional Breach", "Find a Nether structure in the Overworld.", "The Grand Tour", "Visit every single structure added by the mod.", "Haunted Explorer Map", "Nether Explorer Map"); } }
    public static class EN_AU extends LanguageProvider { public EN_AU(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_au"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Digging Days", "G'day! Welcome to the busted factories.", "Spinny Thing", "Find a dodgy old windmill.", "Wind Boss", "See all the spinny things.", "Spooky Story", "Reckon there's ghosts here.", "Ghost Smasher", "Don't die in the spooky spots.", "Rusty Rubbish", "Find some old metal junk.", "Big Iron", "Find all the scrap heaps.", "Map Stuff", "Buy a map from a map bloke.", "Hell Down Under", "Find a shed in the Nether.", "Wrong Place Mate", "Find a hell shed in the bush.", "The Big Walkabout", "Visit every single place, mate.", "Spooky Map", "Hell Map"); } }

    // ================= SLAVIC & BALTIC (THE CORE) =================
    public static class RU extends LanguageProvider { public RU(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "ru_ru"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Эпоха Раскопок", "Добро пожаловать в мир индустриальных руин.", "Дон Кихот", "Найдите любую заброшенную мельницу.", "Повелитель Ветров", "Посетите все типы мельниц.", "Страшилка", "Обнаружьте проклятое место.", "Охотник на привидений", "Выживите во всех проклятых местах.", "Ржавые руины", "Найдите индустриальные останки.", "Тяжелая Промышленность", "Посетите все индустриальные руины.", "Картография", "Купите карту структуры у картографа.", "Адская Экспансия", "Найдите структуру в Аду.", "Пространственный разлом", "Найдите адскую структуру в Верхнем мире.", "Большое Путешествие", "Посетите абсолютно каждую структуру из мода.", "Карта проклятых земель", "Карта адских аванпостов"); } }
    public static class RU_PRE extends LanguageProvider { public RU_PRE(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "ru_pre"); } @Override protected void addTranslations() { addCommon(this, "Create: Строенiя Древнiя", "Лѣтопись Раскопокъ", "Добро пожаловать въ міръ руинъ индустріальныхъ.", "Донъ Кіхотъ", "Отыщи мельницу вѣтряную, временемъ забытую.", "Повелитель Вѣтровъ", "Узри всѣ виды мельницъ.", "Сказъ о Духахъ", "Узри мѣсто проклятое, тьмою объятое.", "Изгоняющiй Бѣсовъ", "Посѣти всѣ мѣста проклятыя.", "Ржавыя Развалины", "Отыщи останки величія механическаго.", "Мануфактура", "Узри всѣ останки величія механическаго.", "Землеописаніе", "Приобрѣти карту заморскую у купца-чертежника.", "Адское Расширеніе", "Ступи ногою своею въ чертоги огненныя.", "Разломъ Мірозданія", "Узри строенiе адское посреди луговъ зелёныхъ.", "Великое Хожденіе", "Посѣти всякое строенiе, мастерами возведенное.", "Карта Земель Проклятыхъ", "Карта Аванпостовъ Адскихъ"); } }
    public static class RU_RY extends LanguageProvider { public RU_RY(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "ru_ry"); } @Override protected void addTranslations() { addCommon(this, "Create: Переробка Будов", "Епоха Копаня", "Вітайте у світі індустріальных руїн.", "Дон Кіхот", "Найдете даякий забутый вітряк.", "Владарь Вітрів", "Навщівте вшыткы типы вітряків.", "Страшная повістка", "Обявте проклятое місто.", "Ловець духов", "Пережыйте вшыткы страшны міста.", "Зарджавілы руїны", "Найдете індустріальны остаткы.", "Тяжка Індустрія", "Навщівте вшыткы індустріальны руїны.", "Картографія", "Купте карту будовы у картографа.", "Пекельна Експанзія", "Найдете будову у Пеклі.", "Просторовый злом", "Найдете пекельну будову на Землі.", "Велика Путь", "Навщівте кажду будову з моду.", "Карта проклятых земель", "Карта пекельных аванпостів"); } }
    public static class UA extends LanguageProvider { public UA(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "uk_ua"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Епоха Розкопок", "Ласкаво просимо у світ індустріальних руїн.", "Дон Кіхот", "Знайдіть будь-який покинутий млин.", "Володар Вітрів", "Відвідайте всі типи млинів.", "Страшилка", "Знайдіть прокляте місце.", "Мисливець на привидів", "Відвідайте всі прокляті місця.", "Іржаві руїни", "Знайдіть індустріальні залишки.", "Важка Промисловість", "Відвідайте всі індустріальні руїни.", "Картографія", "Купіть карту структури у картографа.", "Пекельна Експансія", "Знайдіть структуру в Пеклі.", "Просторовий розлом", "Знайдіть пекельну структуру у Верхньому світі.", "Велика Подорож", "Відвідайте абсолютно кожну структуру з моду.", "Мапа проклятих земель", "Мапа пекельних аванпостів"); } }
    public static class UA_GAL extends LanguageProvider { public UA_GAL(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "uk_gl"); } @Override protected void addTranslations() { addCommon(this, "Create: Файна Архітектура", "Час Копання", "Вітаємо в світі старих залізяк.", "Впертий як віслюк", "Знайди якогось старого вітряка.", "Панич Вітрів", "Знайди всі вітряки, шо є.", "То щось страшне", "Знайди хату з дідьками.", "Виганяйло", "Зайди в кожну страшну хату і не вмри.", "Іржаве Гратя", "Знайди якесь старе залізяччя.", "Пан Фабрикант", "Обійди всі старі фабрики.", "Мапування", "Купи папір у того мудрого в окулярах.", "Пекло і Пательня", "Знайди щось в Пеклі.", "Дідько в хату", "Знайди пекельну хижу на зеленій траві.", "Велика Дефіляда", "Обійди кожну халупу з цього моду.", "Мапа страшних місць", "Мапа пекельних кутів"); } }
    public static class PL extends LanguageProvider { public PL(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "pl_pl"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Era Wykopalisk", "Witamy w świecie przemysłowych ruin.", "Don Kichot", "Znajdź opuszczony wiatrak.", "Władca Wiatrów", "Odwiedź każdy rodzaj wiatraka.", "Opowieść o Duchach", "Odkryj nawiedzone miejsce.", "Pogromca Duchów", "Przetrwaj w każdej nawiedzonej strukturze.", "Zardzewiałe Ruiny", "Znajdź pozostałości przemysłowe.", "Przemysł Ciężki", "Odwiedź wszystkie pozostałości przemysłowe.", "Kartografia", "Kup mapę struktury od kartografa.", "Piekielna Ekspansja", "Znajdź strukturę w Netherze.", "Wyłom Wymiarowy", "Znajdź strukturę z Netheru w zwykłym świecie.", "Wielka Podróż", "Odwiedź każdą strukturę dodaną przez mod.", "Mapa nawiedzonego odkrywcy", "Mapa odkrywcy Netheru"); } }
    public static class CZ extends LanguageProvider { public CZ(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "cs_cz"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Věk Vykopávek", "Vítejte ve světě průmyslových ruin.", "Don Quijote", "Najdi opuštěný větrný mlýn.", "Pán Větrů", "Navštiv všechny typy větrných mlýnů.", "Duchařský Příběh", "Objev strašidelné místo.", "Krotitel duchů", "Přežij ve všech strašidelných strukturách.", "Rezavé Ruiny", "Najdi průmyslové pozůstatky.", "Těžký Průmysl", "Navštiv všechny průmyslové pozůstatky.", "Kartografia", "Kup mapu struktury od kartografa.", "Pekelná Expanze", "Najdi strukturu v Netheru.", "Dimenzionální Trhlina", "Najdi Netherskou strukturu v normálním světě.", "Velká Cesta", "Navštiv každou strukturu přidanou modem.", "Strašidelná mapa průzkumníka", "Mapa průzkumníka Netheru"); } }

    // ================= GERMANIC & NORDIC =================
    public static class DE extends LanguageProvider { public DE(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "de_de"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Das Zeitalter der Ausgrabung", "Willkommen in der Welt der industriellen Ruinen.", "Don Quijote", "Finde eine verlassene Windmühle.", "Herr der Winde", "Besuche jede Art von Windmühle.", "Geistergeschichte", "Entdecke einen verwunschenen Ort.", "Geisterjäger", "Überlebe jede verwunschene Struktur.", "Rostige Ruinen", "Finde ein industrielles Überbleibsel.", "Schwerindustrie", "Besuche alle industriellen Überbleibsel.", "Kartografie", "Kaufe eine Strukturkarte von einem Kartografen.", "Höllische Erweiterung", "Finde eine Struktur im Nether.", "Dimensionsbruch", "Finde eine Nether-Struktur in der Oberwelt.", "Die Große Tour", "Besuche jede einzelne Struktur aus dem Mod.", "Verwunschene Entdeckerkarte", "Nether-Entdeckerkarte"); } }
    public static class NL extends LanguageProvider { public NL(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "nl_nl"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Het Tijdperk van Opgravingen", "Welkom in de wereld van industriële ruïnes.", "Don Quichot", "Vind een verlaten windmolen.", "Heer van de Winden", "Bezoek elk type windmolen.", "Spookverhaal", "Ontdek een spookachtige locatie.", "Ghostbuster", "Overleef elke spookachtige structuur.", "Roestige Ruïnes", "Vind een industrieel overblijfsel.", "Zware Industrie", "Bezoek alle industriële overblijfselen.", "Cartografie", "Koop een structuurkaart van een cartograaf.", "Helse Uitbreiding", "Vind een structuur in de Nether.", "Dimensionale Breuk", "Vind een Nether-structuur in de Overworld.", "De Grote Tour", "Bezoek elke structuur uit de mod.", "Spookachtige Ontdekkingskaart", "Nether Ontdekkingskaart"); } }
    public static class SV extends LanguageProvider { public SV(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "sv_se"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Utgrävningens Tidsålder", "Välkommen till en värld av industriella ruiner.", "Don Quijote", "Hitta en övergiven väderkvarn.", "Vindarnas Herre", "Besök varje typ av väderkvarn.", "Spökhistoria", "Upptäck en hemsökt plats.", "Spökjägare", "Överlev varje hemsökt struktur.", "Rostiga Ruiner", "Hitta en industriell kvarleva.", "Tung Industri", "Besök alla industriella kvarlevor.", "Kartografi", "Köp en strukturkarta från en kartritare.", "Helvetisk Expansion", "Hitta en struktur i Nether.", "Dimensionell Reva", "Hitta en Nether-struktur i Övervärlden.", "Den Stora Turen", "Besök varenda struktur från modden.", "Hemsökt Utforskningskarta", "Nether Utforskningskarta"); } }

    // ================= ROMANCE =================
    public static class FR extends LanguageProvider { public FR(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "fr_fr"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "L'Ère de l'Excavation", "Bienvenue dans le monde des ruines industrielles.", "Don Quichotte", "Trouvez un moulin à vent abandonné.", "Seigneur des Vents", "Visitez tous les types de moulins.", "Histoire de Fantôme", "Découvrez un lieu hanté.", "Chasseur de Fantômes", "Survivez à toutes les structures hantées.", "Ruines Rouillées", "Trouvez un vestige industriel.", "Industrie Lourde", "Visitez tous les vestiges industriels.", "Cartographie", "Achetez une carte de structure à un cartographe.", "Extension Infernale", "Trouvez une structure dans le Nether.", "Brèche Dimensionnelle", "Trouvez une structure du Nether dans l'Overworld.", "Le Grand Tour", "Visitez absolument toutes les structures du mod.", "Carte d'explorateur hantée", "Carte d'explorateur du Nether"); } }
    public static class ES extends LanguageProvider { public ES(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "es_es"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "La Era de la Excavación", "Bienvenido al mundo de las ruinas industriales.", "Don Quijote", "Encuentra cualquier molino de viento abandonado.", "Señor de los Vientos", "Visita todos los tipos de molinos.", "Historia de Fantasmas", "Descubre un lugar embrujado.", "Cazafantasmas", "Sobrevive a todas las estructuras embrujadas.", "Ruinas Oxidadas", "Encuentra un remanente industrial.", "Industria Pesada", "Visita todos los remanentes industriales.", "Cartografía", "Compra un mapa de estructura a un cartógrafo.", "Expansión Infernal", "Encuentra una estructura en el Nether.", "Brecha Dimensional", "Encuentra una estructura del Nether en el Overworld.", "El Gran Tour", "Visita cada una de las estructuras del mod.", "Mapa de Explorador Embrujado", "Mapa de Explorador del Nether"); } }
    public static class ES_MX extends LanguageProvider { public ES_MX(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "es_mx"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "La Era de la Excavación", "Bienvenido al mundo de las ruinas industriales.", "Don Quijote", "Encuentra cualquier molino de viento abandonado.", "Señor de los Vientos", "Visita todos los tipos de molinos.", "Historia de Fantasmas", "Descubre un lugar embrujado.", "Cazafantasmas", "Sobrevive a todas las estructuras embrujadas.", "Ruinas Oxidadas", "Encuentra un remanente industrial.", "Industria Pesada", "Visita todos los remanentes industriales.", "Cartografía", "Compra un mapa de estructura a un cartógrafo.", "Expansión Infernal", "Encuentra una estructura en el Nether.", "Brecha Dimensional", "Encuentra una estructura del Nether en el Overworld.", "El Gran Tour", "Visita cada una de las estructuras del mod.", "Mapa de Explorador Embrujado", "Mapa de Explorador del Nether"); } }
    public static class PT extends LanguageProvider { public PT(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "pt_pt"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "A Era da Escavação", "Bem-vindo ao mundo das ruínas industriais.", "Dom Quixote", "Encontre qualquer moinho de vento abandonado.", "Senhor dos Ventos", "Visite todos os tipos de moinhos.", "História de Fantasma", "Descubra um local assombrado.", "Caça-Fantasmas", "Sobreviva a todas as estruturas assombradas.", "Ruínas Enferrujadas", "Encontre um remanescente industrial.", "Indústria Pesada", "Visite todos os remanescentes industriais.", "Cartografia", "Compre um mapa de estrutura de um cartógrafo.", "Expansão Infernal", "Encontre uma estrutura no Nether.", "Brecha Dimensional", "Encontre uma estrutura do Nether no Overworld.", "O Grande Tour", "Visite todas as estruturas do mod.", "Mapa de Explorador Assombrado", "Mapa de Explorador do Nether"); } }
    public static class BR extends LanguageProvider { public BR(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "pt_br"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "A Era da Escavação", "Bem-vindo ao mundo das ruínas industriais.", "Dom Quixote", "Encontre qualquer moinho de vento abandonado.", "Senhor dos Ventos", "Visite todos os tipos de moinhos.", "História de Fantasma", "Descubra um local assombrado.", "Caça-Fantasmas", "Sobreviva a todas as estruturas assombradas.", "Ruínas Enferrujadas", "Encontre um remanescente industrial.", "Indústria Pesada", "Visite todos os remanescentes industriais.", "Cartografia", "Compre um mapa de estrutura de um cartógrafo.", "Expansão Infernal", "Encontre uma estrutura no Nether.", "Brecha Dimensional", "Encontre uma estrutura do Nether no Overworld.", "O Grande Tour", "Visite todas as estruturas do mod.", "Mapa de Explorador Assombrado", "Mapa de Explorador do Nether"); } }
    public static class IT extends LanguageProvider { public IT(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "it_it"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "L'Era degli Scavi", "Benvenuti nel mondo delle rovine industriali.", "Don Chisciotte", "Trova un mulino a vento abbandonato.", "Signore dei Venti", "Visita tutti i tipi di mulini.", "Storia di Fantasmi", "Scopri un luogo infestato.", "Acchiappafantasmi", "Sopravvivi a tutte le strutture infestate.", "Rovine Arrugginite", "Trova un residuo industriale.", "Industria Pesante", "Visita tutti i residui industriali.", "Cartografia", "Compra una mappa della struttura da un cartografo.", "Espansione Infernale", "Trova una struttura nel Nether.", "Breccia Dimensionale", "Trova una struttura del Nether nell'Overworld.", "Il Gran Tour", "Visita ogni singola struttura del mod.", "Mappa da esploratore infestata", "Mappa da esploratore del Nether"); } }

    // ================= ASIAN & TURKISH =================
    public static class CN extends LanguageProvider { public CN(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "zh_cn"); } @Override protected void addTranslations() { addCommon(this, "机械动力：结构重制", "挖掘时代", "欢迎来到工业废墟的世界。", "堂吉诃德", "找到任何废弃的风车。", "风之领主", "访问所有类型的风车。", "鬼故事", "发现一个闹鬼的地方。", "捉鬼敢死队", "在所有闹鬼的结构中幸存。", "生锈的废墟", "寻找工业遗迹。", "重工业", "访问所有工业遗迹。", "制图学", "从制图师那里购买结构地图。", "地狱扩张", "在下界找到一个结构。", "维度裂缝", "在主世界找到一个下界结构。", "盛大巡游", "访问模组添加的每一个结构。", "闹鬼之地探险家地图", "下界前哨探险家地图"); } }
    public static class TW extends LanguageProvider { public TW(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "zh_tw"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "挖掘時代", "歡迎來到工業廢墟的世界。", "唐吉訶德", "找到任何廢棄的風車。", "風之領主", "參觀所有類型的風車。", "鬼故事", "發現一個鬧鬼的地方。", "捉鬼敢死隊", "在所有鬧鬼的結構中倖存。", "生鏽的廢墟", "尋找工業遺跡。", "重工業", "參觀所有工業遺跡。", "製圖學", "從製圖師那裡購買結構地圖。", "地獄擴張", "在下界找到一個結構。", "維度裂縫", "在主世界找到一個下界結構。", "盛大巡遊", "參觀模組添加的每一個結構。", "鬧鬼之地探險家地圖", "下界前哨探險家地圖"); } }
    public static class JP extends LanguageProvider { public JP(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "ja_jp"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "発掘の時代", "産業遺跡の世界へようこそ。", "ドン・キホーテ", "放棄された風車を見つける。", "風の王", "すべての種類の風車を訪れる。", "怪談", "呪われた場所を発見する。", "ゴーストバスター", "すべての呪われた構造物で生き残る。", "錆びた廃墟", "産業の遺構を見つける。", "重工業", "すべての産業遺構を訪れる。", "地図作製", "製図家から構造物の地図を購入する。", "地獄の拡張", "ネザーで構造物を見つける。", "次元の裂け目", "オーバーワールドでネザーの構造物を見つける。", "グランドツアー", "Modによって追加されたすべての構造物を訪れる。", "呪われた探検家の地図", "ネザー探検家の地図"); } }
    public static class KR extends LanguageProvider { public KR(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "ko_kr"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "발굴의 시대", "산업 폐허의 세계에 오신 것을 환영합니다.", "돈키호테", "버려진 풍차를 찾으세요.", "바람의 군주", "모든 종류의 풍차를 방문하세요.", "괴담", "유령이 나오는 장소를 발견하세요.", "고스트버스터", "모든 유령 구조물에서 살아남으세요.", "녹슨 폐허", "산업 잔해를 찾으세요.", "중공업", "모든 산업 잔해를 방문하세요.", "지도 제작", "지도 제작자에게서 구조물 지도를 구매하세요.", "지옥 확장", "네더에서 구조물을 찾으세요.", "차원의 균열", "오버월드에서 네더 구조물을 찾으세요.", "그랜드 투어", "모드에 추가된 모든 구조물을 방문하세요.", "유령 탐험가 지도", "네더 탐험가 지도"); } }
    public static class TR extends LanguageProvider { public TR(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "tr_tr"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "Kazı Çağı", "Endüstriyel kalıntıların dünyasına hoş geldin.", "Don Kişot", "Terk edilmiş bir yel değirmeni bul.", "Rüzgarın Efendisi", "Her tür yel değirmenini ziyaret et.", "Hayalet Hikayesi", "Perili bir yer keşfet.", "Hayalet Avcısı", "Tüm perili yapılardan sağ çık.", "Paslı Harabeler", "Endüstriyel bir kalıntı bul.", "Ağır Sanayi", "Tüm endüstriyel kalıntıları ziyaret et.", "Haritacılık", "Haritacıdan bir yapı haritası satın al.", "Cehennem Genişlemesi", "Nether'da bir yapı bul.", "Boyutsal Yarık", "Dünyada bir Nether yapısı bul.", "Büyük Tur", "Moddaki her bir yapıyı ziyaret et.", "Perili Kaşif Haritası", "Nether Kaşif Haritası"); } }

    // ================= FUN & CONSTRUCTED =================
    public static class PIRATE extends LanguageProvider { public PIRATE(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_pt"); } @Override protected void addTranslations() { addCommon(this, "Create: Ye Olde Structures", "The Age o' Diggin'", "Welcome to the lands o' rusty treasure.", "Chasin' the Wind", "Spy an abandoned windmill, yarr.", "Lord o' the Sails", "Spy every kind of windmill.", "Ghost Ship... on Land?", "Find a place cursed by Davy Jones.", "Ghost Buster", "Plunder every accursed place.", "Rusty Booty", "Find some old iron contraptions.", "Heavy Industry", "Visit every bit o' scrap.", "X Marks the Spot", "Barter for a map with a landlubber.", "Brimstone Expansion", "Sail into the fiery depths.", "The Devils are Here", "Find a piece of Hell in the seven seas.", "Captain of the World", "Set foot in every single ruin, ye legend.", "Cursed Treasure Map", "Hellish Treasure Map"); } }
    public static class LOL extends LanguageProvider { public LOL(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "lol_us"); } @Override protected void addTranslations() { addCommon(this, "Create: Strucshurs", "Teh Age of Diggin", "Oh hai! Welcome to rusty placez.", "Spinny Boi", "I can haz windmill?", "Lord of Spinnies", "See ALL teh spinny bois.", "Spooktober", "Find 2spooky4me place.", "Ghoztbustr", "No die in spooky house.", "Rust Bucket", "Find old metal thingz.", "Big Factory", "See ALL teh metal thingz.", "Mapz", "Buy paper from villager dood.", "Hot Place", "Go to red place found fing.", "Whut is dis?", "Find red place house in green place. Ooooooooooohhhhh blue tingy!", "I has seen evryfing", "Go to ALL teh places!", "Spooky Map", "Hot Map"); } }
    public static class UD extends LanguageProvider { public UD(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_ud"); } @Override protected void addTranslations() { addCommon(this, "lnɐɥɹǝʌO sǝɹnʇɔnɹʇS :ǝʇɐǝɹƆ", "uoᴉʇɐʌɐɔxƎ ɟo ǝƃ∀ ǝɥ┴", "˙suᴉnɹ lɐᴉɹʇsnpuᴉ ɟo plɹoʍ ǝɥʇ oʇ ǝɯoɔlǝM", "ǝʇoxᴉnQ uop", "˙llᴉɯpuᴉʍ pǝuopuɐqɐ ʎuɐ puᴉℲ", "spuᴉM ǝɥʇ ɟo pɹo˥", "˙llᴉɯpuᴉʍ ɟo ǝdʎʇ ʎɹǝʌǝ ʇᴉsᴉΛ", "ʎɹoʇS ʇsoɥפ", "˙uoᴉʇɐɔol pǝʇunɐɥ ɐ ɹǝʌoɔsᴉp", "ɹǝʇsnqʇsoɥפ", "˙ǝɹnʇɔnɹʇs pǝʇunɐɥ ʎɹǝʌǝ ǝʌᴉʌɹnS", "suᴉnᴚ ʎʇsnᴚ", "˙ʇuɐuɯǝɹ lɐᴉɹʇsnpuᴉ uɐ puᴉℲ", "ʎɹʇsnpuI ʎʌɐǝH", "˙ʇuɐuɯǝɹ lɐᴉɹʇsnpuᴉ ʎɹǝʌǝ ʇᴉsᴉΛ", "ʎɥdɐɹƃoʇɹɐƆ", "˙ɹǝɥdɐɹƃoʇɹɐƆ ɐ ɯoɹɟ dɐɯ ǝɹnʇɔnɹʇs ɐ ʎnq", "uoᴉsuɐdxƎ ɥsᴉllǝH", "˙ɹǝɥʇǝN ǝɥʇ uᴉ ǝɹnʇɔnɹʇs ɐ puᴉℲ", "ɥɔɐǝɹq lɐuoᴉsuǝɯᴉp", "˙plɹoʍɹǝʌO ǝɥʇ uᴉ ǝɹnʇɔnɹʇs ɹǝɥʇǝN ɐ puᴉℲ", "ɹno┴ puɐɹפ ǝɥ┴", "˙poɯ ǝɥʇ ʎq pǝppɐ ǝɹnʇɔnɹʇs ǝlƃuᴉs ʎɹǝʌǝ ʇᴉsᴉΛ", "dɐW ɹǝɹoldxƎ pǝʇunɐH", "dɐW ɹǝɹoldxƎ ɹǝɥʇǝN"); } }
    public static class WS extends LanguageProvider { public WS(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "en_ws"); } @Override protected void addTranslations() { addCommon(this, "Create: Structures Overhaul", "The Age of Delving", "Hail and well met in this realm of ruin.", "Tilting at Windmills", "Espy a forsaken mill of wind.", "Lord of the Zephyrs", "Visit every manner of windmill.", "A Tale of Spirits", "Discover a place most haunted.", "Spirit Walker", "Survive all manner of cursed halls.", "Corroded Remnants", "Find a relic of industry.", "Great Works", "Visit every relic of industry.", "Cartography", "Purchase a chart from a scribe.", "Infernal Growth", "Find a structure in the Abyss.", "Planar Rift", "Find an Infernal structure upon the earth.", "The Grand Pilgrimage", "Visit every single edifice herein.", "Cursed Chart", "Infernal Chart"); } }
    public static class TLH extends LanguageProvider { public TLH(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "tlh_aa"); } @Override protected void addTranslations() { addCommon(this, "Create: ChenmoH Strucshurs", "Bogh Excavation", "NuqneH! Welcome to ruins of honor.", "Don Quixote", "Sam abandoned SuvwI' mill.", "JoH of Winds", "GhoS all types of windmills.", "Ghost Lut", "Tu' haunted daq.", "Ghost Hunter", "TaH in every haunted structure.", "Qij Ruins", "Sam industrial relics.", "Heavy Industry", "GhoS all industrial relics.", "Cartography", "Je' structure map from Cartographer.", "Ghe''or Expansion", "Sam structure in Nether.", "Dimensional Breach", "Sam Nether structure in Overworld.", "The Grand Tour", "GhoS every single structure added by mod.", "Haunted Explorer Map", "Nether Explorer Map"); } }
    public static class QYA extends LanguageProvider { public QYA(PackOutput output) { super(output, CreateStructuresOverhaulMod.MODID, "qya_aa"); } @Override protected void addTranslations() { addCommon(this, "Create: Carë Structures", "Yéni of Excavation", "Mae govannen! Welcome to industrial ruins.", "Don Quixote", "Hir- abandoned windmill.", "Heru of Súlimë", "Ceni- all types of windmills.", "Faë Narn", "Hir- gaer location.", "Faë Fara-", "Cuila- in every haunted structure.", "Rauca Ruins", "Hir- industrial remnant.", "Tungl Industry", "Ceni- all industrial remnants.", "Cartography", "Boh- structure map from Cartographer.", "Udûn Expansion", "Hir- structure in Nether.", "Dimensional Breach", "Hir- Nether structure in Ambar.", "The Grand Tour", "Ceni- every single structure added by mod.", "Haunted Explorer Map", "Nether Explorer Map"); } }
}