plugins {
    id 'java'
    id 'dev.architectury.loom' version '1.7-SNAPSHOT'
}

version = "3.0.0"
group = "net.denmoth.createstructuresoverhaul"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

sourceSets {
    main {
        resources {
            srcDir project.file('../common/src/main/resources')
        }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases/' }
    maven { url = "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.officialMojangMappings()

    neoForge "net.neoforged:neoforge:21.1.10"
    modCompileOnly "me.shedaniel.cloth:cloth-config-neoforge:15.0.127"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def expandProps = [
        "mod_id": "cso",
        "mod_version": "3.0.0",
        "mod_name": "Create: Structures Overhaul",
        "mod_license": "MIT",
        "mod_authors": "Denmoth",
        "mod_description": "Overhauls exploration by adding immersive, Create-themed structures to the world.",
        "loader_version_range": "[47,)",
        "minecraft_version_range": "[1.21.1]",
        "forge_version_range": "[47,)",
        "neoforge_version_range": "[21.1,)"
    ]
    inputs.properties expandProps
    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand expandProps
    }
    doLast {
        def destDir = file("$buildDir/resources/main/data/cso")
        if (file("$destDir/structures").exists()) file("$destDir/structures").renameTo(file("$destDir/structure"))
        if (file("$destDir/advancements").exists()) file("$destDir/advancements").renameTo(file("$destDir/advancement"))
        if (file("$destDir/loot_tables").exists()) file("$destDir/loot_tables").renameTo(file("$destDir/loot_table"))
    }
}

jar {
    exclude 'net/minecraftforge/**'
    exclude 'net/neoforged/**'
}